# start the demo with
#   docker-compose -f docker-compose.cloner.yml up
services:

    orthanc-a:
        image: orthancteam/orthanc
        ports: ["8042:8042"]
        environment:
            ORTHANC__AUTHENTICATION_ENABLED: "false"
            ORTHANC__NAME: "A"
        volumes: ["orthanc-storage-a:/var/lib/orthanc/db"]
        restart: unless-stopped

    orthanc-b:
        image: orthancteam/orthanc
        ports: ["8043:8042"]
        environment:
            ORTHANC__AUTHENTICATION_ENABLED: "false"
            ORTHANC__NAME: "B"
        volumes: ["orthanc-storage-b:/var/lib/orthanc/db"]
        restart: unless-stopped

    orthanc-cloner:
        image: orthancteam/python-orthanc-tools:0.19.1
        volumes: ["orthanc-cloner:/status"]
        environment:
#            TZ: "Etc/UTC"
            TZ: "Europe/Paris"
            RUN_SCHEDULE: '{"Monday-Saturday": ["0-7", "18-24"], "Sunday": ["0-24"]}'
            SOURCE_URL: "http://orthanc-a:8042"
#            SOURCE_USER: "user"
#            SOURCE_PWD: "pwd"
            DEST_URL: "http://orthanc-b:8042"
#            DEST_USER: "user"
#            DEST_PWD: "pwd"
            MODE: "Default"
            PERSIST_STATE_PATH: "/status/status.txt"
            WORKER_THREADS_COUNT: "24"
#            VERBOSE_ENABLED: "true"
        entrypoint: python -m orthanc_tools.orthanc_cloner
volumes:
    orthanc-cloner:
    orthanc-storage-a:
    orthanc-storage-b:
